### ISSUE TITLE
Query vector reshaping causes issues. 

### ISSUE THREAD

**Issue by alexndrvega** [alexndrvega/HugVector#8]
The dimensions of the query vector and the indexed vectors need to be checked to find a possible solution.

**Comment by alexndrvega** [comment]
``` Traceback (most recent call last):
  File "/HugVector/examples/text_example.py", line 56, in <module>
    distances, results = hug_db_replicas[0].search(query_vector.reshape(1, -1), k=2, metadata_filter=metada_filter)
  File "/HugVector/examples/../src/hug_db.py", line 58, in search
    distances, indices = self.index.search(query_vector, k)
  File "/HugVector/lib/python3.10/site-packages/faiss/class_wrappers.py", line 329, in replacement_search
    assert d == self.d
AssertionError ```

**Comment by alexndrvega** [comment]
The issue was being cused by the the number of training points provided. 
Traning points need to be increased to 9984:

`WARNING clustering 4049 points to 256 centroids: please provide at least 9984 training points`

```
Query vector before re-shape: [-4.81567383e-02  8.23364258e-02  1.43778488e-01  1.09212242e-01
 -1.23555504e-01  3.11838780e-02 -9.55200195e-03  1.13606773e-01
 -9.59472656e-02  1.46931961e-01 -6.96207657e-02 -1.68416336e-01
 -2.44710281e-01  2.56673187e-01 -4.64680977e-02  1.77571610e-01
  1.62841797e-01  1.70003250e-01  1.12202959e-02 -3.74348946e-02
 -2.68981934e-01 -1.01928711e-02  2.08089188e-01 -9.42789689e-02
 -2.52034515e-01 -8.54492188e-03 -1.01236977e-01  1.66127518e-01
 -1.01481117e-01  1.01725257e-03  9.44465026e-02  1.71457931e-01
 -5.95296212e-02 -9.54996720e-02 -1.49495438e-01 -4.64363098e-02
 -3.17586251e-02  2.76570648e-01  1.68945312e-01 -3.13415527e-02
  1.71101883e-01 -8.85823593e-02  3.02246094e-01  1.19873047e-01
  1.16978966e-01 -1.54988602e-01 -1.10397339e-01 -9.43501815e-02
 -1.98303223e-01  2.02799484e-01 -1.16292320e-01  7.81656876e-02
 -6.23474121e-02  7.75553361e-02 -2.96427403e-02  8.29671249e-02
 -2.62369782e-01 -9.20003280e-02  8.23974609e-02 -8.93961564e-02
 -1.25000000e-01  1.20076500e-01 -1.53055832e-01  7.73111999e-04
  1.38163254e-01 -2.21923828e-01 -5.02586365e-02 -1.16007484e-01
  6.02213526e-03  4.51037101e-02  1.50797531e-01  1.53757734e-02
  7.47439042e-02  8.61409530e-02 -1.76269531e-01 -5.28157540e-02
  7.85827637e-02  1.28784180e-01 -8.94368514e-02 -7.78198242e-02
 -1.76920578e-01  1.49154663e-01 -9.73307267e-02 -3.31217460e-02
  8.43912736e-02  2.86051422e-01 -6.12996407e-02  1.97591141e-01
  3.13720703e-02 -1.92159023e-02 -4.55474854e-02  9.11458302e-03
 -4.25542183e-02 -1.67846680e-01 -1.97296143e-02 -2.64396667e-02
 -1.70288086e-02 -6.48752833e-03  9.56624374e-02 -1.64225265e-01
 -4.41996269e-02  7.67415389e-02  1.52852371e-01 -5.98551445e-02
 -1.21765137e-01  1.87138870e-01 -1.59240723e-01  2.51139313e-01
  1.70898438e-02 -6.35782853e-02 -3.18196625e-01 -1.96329758e-01
  3.43831368e-02 -9.65067521e-02  7.83691406e-02  1.85546875e-02
  1.11971535e-01 -2.95410156e-01  1.57089233e-02  1.38339356e-01
  2.14111328e-01  1.54052734e-01 -4.89908867e-02 -1.01928711e-01
  2.60172516e-01 -1.13067627e-01 -1.77897140e-01 -3.17382812e-02
  5.61523438e-02 -6.89290389e-02 -2.07519531e-01  6.42293319e-02
  2.79541016e-02  1.16099037e-01 -1.45874023e-01  1.41520187e-01
 -9.99959335e-02  6.70979843e-02  3.23079437e-01  1.07340492e-01
  1.74397781e-01 -8.99403915e-02 -1.23972572e-01 -1.47989914e-01
 -2.18750000e-01  1.80257168e-02 -1.90376282e-01  1.58040360e-01
  3.83300781e-02 -9.51741561e-02  8.03019181e-02 -1.50451660e-01
 -1.59510300e-01 -4.66715507e-02  2.15047207e-02 -8.57747421e-02
 -4.23278809e-02  4.13411468e-01  3.50062065e-02 -2.24609375e-01
  1.17248535e-01  1.97102860e-01  1.19628906e-02 -6.07452393e-02
  1.23148598e-01 -2.12768555e-01  9.46858749e-02 -3.91235352e-02
 -1.47684738e-01  4.71242256e-02 -1.62841797e-01  8.56475830e-02
 -1.55436201e-02 -3.07388306e-02 -2.14029942e-02  4.69970703e-02
  3.17301422e-01 -1.86035156e-01  1.93115234e-01 -1.08723961e-01
 -2.73437500e-02  7.03007355e-02  1.58284500e-01  5.55775948e-02
  8.12403336e-02  3.37402344e-01 -5.53906746e-02 -2.14843750e-02
 -7.48030320e-02  5.41992188e-02  1.34114578e-01  6.47989884e-02
 -1.53686523e-01  1.31490067e-01  9.49707031e-02 -1.83105469e-04
  2.69775391e-02  1.86767578e-02 -5.78816719e-02  4.30552848e-02
 -2.18750000e-01 -2.11995449e-02 -4.37291451e-02 -1.74926758e-01
 -6.09080009e-02 -1.15152992e-01  9.36686173e-02  1.64896641e-02
 -1.92464199e-02 -7.20723495e-02  1.34653732e-01 -1.31479902e-02
 -2.53906250e-01  1.19018555e-03 -9.32210311e-02 -8.68225098e-02
  2.23363247e-02 -2.10286453e-01  5.84869385e-02 -1.23942055e-01
 -1.76228836e-01  1.39282227e-01  1.56311035e-01  4.28466797e-02
  1.29638672e-01  5.31514501e-03  1.37430832e-01  6.80643693e-02
  7.03938827e-02 -1.43218994e-01 -6.94681779e-02 -3.52528878e-02
 -1.32486984e-01  1.10717773e-01  1.44500732e-02 -3.29132080e-02
 -3.89251709e-02  9.87447128e-02  1.32609054e-01  6.47074357e-02
 -8.19905624e-02  2.39054356e-02  1.09659828e-01  6.04629517e-02
 -6.13606758e-02 -8.53678361e-02 -7.17875138e-02  3.14290375e-01
 -7.64567032e-02 -8.01696777e-02  9.04947892e-02  8.68123397e-02
  2.21313477e-01  1.77978516e-01  2.16878261e-02 -2.92399079e-01
 -1.40919998e-01 -3.02937832e-02  1.13362633e-01  2.02189133e-01
  1.26139319e-03  1.75537109e-01  1.60847977e-01 -2.25931797e-02
 -1.31754562e-01 -1.17777504e-01  5.92091866e-02  5.10457344e-02
  7.65991211e-02 -1.68294266e-01 -2.17203781e-01  6.36316910e-02
 -1.74446106e-02  8.93147811e-02  1.04003906e-01 -7.30285645e-02
 -2.18505859e-01 -1.09700523e-01 -2.40153000e-01  2.19726562e-01
 -6.51448593e-02  4.46319580e-02  1.61092117e-01 -1.00179039e-01
  2.37874344e-01  1.68457031e-02  1.72159836e-01  1.23775959e-01
 -9.74934921e-02  6.06282540e-02  9.63134766e-02  8.03680420e-02
 -4.01611328e-02  1.61824539e-01 -1.32446289e-01 -1.70288086e-01
 -8.19905624e-02 -3.01615391e-02 -1.37654617e-01  2.23632812e-01]
Query vector shape after reshape: (1, 300)
Indexed vectors dimension: 300
```

**Comment by alexndrvega** [comment]
Issue resolved.
